name: Build Bluetooth Mouse Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MSYS2
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-gcc

    - name: Build executable
      shell: msys2 {0}
      run: |
        g++ main.cpp -o bluetooth_server.exe -lws2_32 -lbthprops

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bluetooth_server_exe
        path: bluetooth_server.exe
