name: Build Bluetooth Mouse Server (Nader)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        version: latest
        platform: x64

    - name: Build executable
      run: |
        g++ main.cpp -o nader_bluetooth_server.exe -lws2_32 -lbthprops

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: nader_bluetooth_server_exe
        path: nader_bluetooth_server.exe
